#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE DATABASE tutorial;
	\c tutorial;
    CREATE USER docker WITH ENCRYPTED PASSWORD '123456';
	CREATE SCHEMA IF NOT EXISTS dev AUTHORIZATION docker;
    GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA dev TO docker;
	GRANT ALL PRIVILEGES ON DATABASE tutorial TO docker;
	CREATE EXTENSION IF NOT EXISTS "uuid-ossp"  SCHEMA dev;

EOSQL