version: "3.7"
services:
  postgres-sql:
    image: docker.io/postgres:16-alpine
    container_name: pg
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - data:/var/lib/postgresql/data 
      - export:/export
      - /shared/projects/spring-boot-sandbox/firstcrud/infra/init.sh:/docker-entrypoint-initdb.d/init-db.sh
volumes:
  data:
  export:
