@startuml

interface IUserService{

}

class UserServiceImp implements IUserService {
    - IUserDao userDao;
}

interface IUserDao{

}

class UserDaoImp implements IUserDao {
    
}

class NewUserDaoImp implements IUserDao {
    
}


UserServiceImp ..> IUserDao: Dependency

@enduml