@startuml

interface IUserService{

}

class UserServiceImp implements IUserService {
    - IUserDao userDaoImp = new UserDaoImp();
}

interface IUserDao{

}

class UserDaoImp implements IUserDao {
    
}


UserServiceImp ..> IUserDao: Dependency

@enduml