@startuml

interface IUserService{

}

class UserServiceImp implements IUserService {
    - IUserDao userDaoImp = new NewUserDaoImp();
}

interface IUserDao{

}

class UserDaoImp implements IUserDao {
    
}

class NewUserDaoImp implements IUserDao {
    
}


UserServiceImp ..> NewUserDaoImp: Dependency

@enduml