/*
 * This source file was generated by the Gradle 'init' task
 */
package org.interceptors;

import org.junit.jupiter.api.Test;

import org.junit.jupiter.api.Disabled;

@Disabled
class AppTest {
    @Test void appHasAGreeting() {
      
    }
}
